### ISSUE TITLE
Remove Legacy Cards?

### ISSUE THREAD

**Issue by ronhowe** [swccgpc/holotable#143]
Let the past die.  Kill it if you have to.

The JSON repo has a PR to move the legacy cards out into a separate JSON file for posterity.

Thoughts on officially killing off the legacy cards in Holotable?

We don't have images for them.  They've in various states of errata and what not.

Could we just move on?

**Comment by EchoBaseTrooper** [comment]
No please don't remove them from Holotable.

**Comment by ronhowe** [comment]
Okee dokee
