### ISSUE TITLE
Standardize Effect Ending Text (Immune to Alter.)

### ISSUE THREAD

**Issue by ronhowe** [swccgpc/holotable#240]
The JSON and CDF files have inconsistencies on "(Immune to Alter.)" when it is the last text of an Effect.

Sometimes I see (Immune To Alter.)
Sometimes I see (Immune to Alter)
Sometimes I see [Immune to Alter.]

I'd like to standardize both on (Immune to Alter.) as per Decipher printed text on a great many cards.

Note: This does NOT apply to any other game text references.  This ONLY when these three words and only these three words are the last three words of the game text.

Thoughts?

**Comment by EchoBaseTrooper** [comment]
The square brackets are on virtual cards denoting that it's the Immune to Alter icon instead of spelling out (Immune to Alter.) in the text.
