### ISSUE TITLE
Is Set 13 CDF Support in Progress?

### ISSUE THREAD

**Issue by ronhowe** [swccgpc/holotable#63]
I see Set 13 images are committed.

Has anybody started on the CDF support?

I don't want to waste my time if somebody is already working on it.

Also, is there a script to hash and compress the CDF files (similar to the images script)?

Or do you just run the similar commands and update the version.dat?

Thanks in advance!

**Comment by ronhowe** [comment]
Also, you just approved and merged a PR of mine to fix a few very minor card texts.

This was my attempt of learning how to participate.

I updated the version.dat.

However, when I launch Holotable, I am not being prompted to download the new CDFs.

Do I need to update line 1 of the verison.dat file?

Currently is says 0.9.9.

If I submit a PR for 0.9.12 (to reflect for example that CDF support is up to set 12), would that fix the issue?

Looking to help.

**Comment by DevoKun** [comment]
Hello, Ron.

Holotable is in a bit of a half-broken state at the moment. We are working with the author to get it repaired.

The `version.dat` which is used by **holotable** actually comes from http://www.holotable.com/version.dat, not the file in this git repo. There are some incorrect sha256 sum's in the `version.dat` file on `www.holotable.com`. Hopefully we can get that resolved some time soon.

The version number at the top of the `version.dat` file represents the latest version of the holotable application. The image file list versions are date-based and follow a `YYYYmmdd` format.

The image files are added manually once they are made available by the graphics team.

The graphics indexes are generated automatically by a GitHub action whenever a commit is made, so `listmd5`, and `version.dat` will automatically update to match the current repo contents.

Thank you for your contributions and continued interest in holotable.

**Comment by ronhowe** [comment]
My PowerShell parser is basically ready to provide Set 13 support.  To make sure everything goes well, I submitted a PR with minor tweaks that my parser found inconsistent with the JSON files.

**Comment by ronhowe** [comment]
I will be submitting a PR for Set 13 this week.
