### ISSUE TITLE
Aurra Sing With Blaster Rifle (AI)

### ISSUE THREAD

**Issue by ronhowe** [swccgpc/holotable#80]
Aurra Sing With Blaster Rifle (AI) references image /starwars/Virtual12-Dark/t_aurrasingwithblasterrifleai, which does not exist.

Which option makes sense?

1. Leave it as is.  Holotable will show you a broken image.
2. Remove the card from Holotable.  This would be consistent with JSON.  It does not have this AI card.
3. Reference non-AI image /starwars/Virtual12-Dark/t_aurrasingwithblasterrifle.
4. Find/create/recreate and commit the actual AI image.

I can submit a PR for solution 2 or 3.

4 is up to someone else.

**Comment by EchoBaseTrooper** [comment]
I think 4 is the best solution, but 3 will work for now so I would vote for that.

The existing image is the AI image so the non-AI image is the one that would need to be created.

**Comment by ronhowe** [comment]
OK.  I will submit 3 shortly as a solution until 4 can be completed.

**Comment by DevoKun** [comment]
I added the AI of _"Aurra Sing with Blaster Rifle"_

**Comment by EchoBaseTrooper** [comment]
Technically the images should be swapped. The current AI image is using the non-AI underlying card and vice versa.
